"""
export_policy_weights.py — rebuild of the lost June exporter (export_mlabs.py),
extended for PPO. Emits mtb_ml_weights.lua-format string-blob modules for the
MTB-ML-ABS.lua in-controller NN, and runs an OFFLINE PARITY CHECK by re-parsing
the emitted Lua text and comparing against the SB3 policy on random obs.

Format (reverse-engineered from the deployed mtb_ml_weights.lua):
  M.obs_dim / M.act_dim / M.clip_obs / M.eps
  M.obs_mean_s / M.obs_var_s        VecNormalize stats over the FULL STACKED obs
  M.layers = { {rows,cols, act="relu"|nil, b_s=[==[...]==], W_s=[==[...]==]}, ... }
  W row-major: (r,c) at flat (r-1)*cols+c.  Floats %.9g space-separated.
NEW (PPO): M.head = "sac_tanh01" | "ppo_clip01" | "ppo_axle"; M.axle_cap for ppo_axle.
The controller applies the head AFTER the MLP (SAC path = tanh+unscale->[0,1]).

Usage:
  python export_policy_weights.py --ckpt <model.zip> --vecnorm <vecnormalize.pkl>
      --algo ppo --head ppo_clip01 --out mtb_ml_weights_ppo.lua [--axle-cap 0.0]
"""
import argparse
import pickle
import re

import numpy as np
import torch as th


def fmt(a):
    return " ".join("%.9g" % float(x) for x in np.asarray(a).ravel())


def load_vecnorm(path):
    # pickle is required here: SB3's VecNormalize.save() writes a pickle. These are
    # OUR OWN training artifacts from this machine (trusted), never third-party files.
    with open(path, "rb") as f:
        vn = pickle.load(f)
    return (np.asarray(vn.obs_rms.mean, dtype=np.float64),
            np.asarray(vn.obs_rms.var, dtype=np.float64),
            float(vn.clip_obs), float(vn.epsilon))


def extract_layers(ckpt, algo):
    """Return [(W, b, act), ...] ending with the action head (act=None)."""
    if algo == "ppo":
        from stable_baselines3 import PPO
        model = PPO.load(ckpt, device="cpu")
        pol = model.policy
        seq = list(pol.mlp_extractor.policy_net)          # Linear/ReLU alternating
        layers = []
        for m in seq:
            if isinstance(m, th.nn.Linear):
                layers.append([m.weight.detach().numpy(), m.bias.detach().numpy(), "relu"])
        head = pol.action_net
        layers.append([head.weight.detach().numpy(), head.bias.detach().numpy(), None])
        return layers, model
    else:  # sac
        from stable_baselines3 import SAC
        model = SAC.load(ckpt, device="cpu")
        actor = model.policy.actor
        layers = []
        for m in actor.latent_pi:
            if isinstance(m, th.nn.Linear):
                layers.append([m.weight.detach().numpy(), m.bias.detach().numpy(), "relu"])
        mu = actor.mu
        layers.append([mu.weight.detach().numpy(), mu.bias.detach().numpy(), None])
        return layers, model


def emit_lua(layers, mean, var, clip_obs, eps, head, axle_cap, out_path, src):
    obs_dim = len(mean)
    act_dim = layers[-1][0].shape[0]
    L = []
    L.append("-- %s  (auto-generated by export_policy_weights.py from %s)" % (out_path.split('\\')[-1].split('/')[-1], src))
    L.append("-- head=%s | normalize: clip((x-obs_mean)/sqrt(obs_var+eps), -clip_obs, clip_obs)" % head)
    L.append("-- STRING-BLOB FORMAT (LuaJIT 65,536 number-constant cap safe); W_s ROW-MAJOR (r-1)*cols+c")
    L.append("local M = {}")
    L.append("M.obs_dim = %d" % obs_dim)
    L.append("M.act_dim = %d" % act_dim)
    L.append("M.clip_obs = %g" % clip_obs)
    L.append("M.eps = %g" % eps)
    L.append("M.head = %q" % head if False else 'M.head = "%s"' % head)
    L.append("M.axle_cap = %g" % axle_cap)
    L.append("M.obs_mean_s = [==[%s]==]" % fmt(mean))
    L.append("M.obs_var_s = [==[%s]==]" % fmt(var))
    L.append("M.layers = {")
    for (W, b, act) in layers:
        rows, cols = W.shape
        L.append("  {")
        L.append("    rows=%d, cols=%d,%s" % (rows, cols, ' act="relu",' if act == "relu" else ""))
        L.append("    b_s=[==[%s]==]," % fmt(b))
        L.append("    W_s=[==[%s]==]," % fmt(W))   # torch Linear weight is (out,in) = row-major (r,c)
        L.append("  },")
    L.append("}")
    L.append("return M")
    with open(out_path, "w") as f:
        f.write("\n".join(L))
    return obs_dim, act_dim


# ---------- offline parity: re-parse the EMITTED LUA TEXT and forward ----------
def parse_blob(path):
    txt = open(path).read()
    def grab(name):
        m = re.search(re.escape(name) + r"\s*=\s*\[==\[(.*?)\]==\]", txt, re.S)
        return np.fromstring(m.group(1), sep=" ") if m else None
    mean = grab("M.obs_mean_s"); var = grab("M.obs_var_s")
    clip_obs = float(re.search(r"M\.clip_obs = ([\d.eE+-]+)", txt).group(1))
    eps = float(re.search(r"M\.eps = ([\d.eE+-]+)", txt).group(1))
    layers = []
    for m in re.finditer(r"\{\s*rows=(\d+), cols=(\d+),(.*?)b_s=\[==\[(.*?)\]==\],\s*W_s=\[==\[(.*?)\]==\],", txt, re.S):
        rows, cols = int(m.group(1)), int(m.group(2))
        act = "relu" if 'act="relu"' in m.group(3) else None
        b = np.fromstring(m.group(4), sep=" ")
        W = np.fromstring(m.group(5), sep=" ").reshape(rows, cols)
        layers.append((W, b, act))
    return mean, var, clip_obs, eps, layers


def lua_forward(obs_raw, mean, var, clip_obs, eps, layers, head):
    x = np.clip((obs_raw - mean) / np.sqrt(var + eps), -clip_obs, clip_obs)
    for (W, b, act) in layers:
        x = W @ x + b
        if act == "relu":
            x = np.maximum(x, 0.0)
    if head == "sac_tanh01":
        return (np.tanh(x) + 1.0) * 0.5
    if head == "ppo_clip01":
        return np.clip(x, 0.0, 1.0)
    if head == "ppo_axle":
        return np.clip(x, -1.0, 1.0)   # transform to wheels happens in-controller
    return x


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--ckpt", required=True)
    ap.add_argument("--vecnorm", required=True)
    ap.add_argument("--algo", choices=["ppo", "sac"], default="ppo")
    ap.add_argument("--head", choices=["sac_tanh01", "ppo_clip01", "ppo_axle"], required=True)
    ap.add_argument("--axle-cap", type=float, default=1.0)
    ap.add_argument("--out", required=True)
    ap.add_argument("--n-parity", type=int, default=256)
    args = ap.parse_args()

    mean, var, clip_obs, eps = load_vecnorm(args.vecnorm)
    layers, model = extract_layers(args.ckpt, args.algo)
    obs_dim, act_dim = emit_lua(layers, mean, var, clip_obs, eps,
                                args.head, args.axle_cap, args.out, args.ckpt)
    print("emitted %s  (obs %d -> act %d, %d layers, head=%s)" %
          (args.out, obs_dim, act_dim, len(layers), args.head))

    # parity: SB3 (deterministic) vs re-parsed blob forward, on random NORMALIZED obs
    pm, pv, pc, pe, pl = parse_blob(args.out)
    rng = np.random.default_rng(0)
    raw = rng.normal(loc=mean, scale=np.sqrt(var + eps), size=(args.n_parity, obs_dim))
    worst = 0.0
    for i in range(args.n_parity):
        normed = np.clip((raw[i] - mean) / np.sqrt(var + eps), -clip_obs, clip_obs)
        with th.no_grad():
            a_sb3 = model.policy._predict(
                th.as_tensor(normed, dtype=th.float32).unsqueeze(0),
                deterministic=True).numpy().ravel().astype(np.float64)
        if args.head == "sac_tanh01":
            a_sb3 = (a_sb3 + 1.0) * 0.5    # SAC _predict is tanh-squashed [-1,1]
        elif args.head == "ppo_clip01":
            a_sb3 = np.clip(a_sb3, 0.0, 1.0)
        else:
            a_sb3 = np.clip(a_sb3, -1.0, 1.0)
        a_lua = lua_forward(raw[i], pm, pv, pc, pe, pl, args.head)
        worst = max(worst, float(np.max(np.abs(a_sb3 - a_lua))))
    print("PARITY (SB3 vs emitted-blob forward, %d random obs): max abs diff = %.3g" %
          (args.n_parity, worst))
    print("PASS" if worst < 1e-5 else "FAIL — investigate before deploying!")


if __name__ == "__main__":
    main()
